### ISSUE TITLE
LexiconNerMultipleFile seems to hang on two files

### ISSUE THREAD

**Issue by kwalcock** [clulab/habitus#160]
It may be related to recent changes to NumericEntityRecognizer in processors, because the problem hasn't been noticed before.  This was on a locally published masters branch of processors and a habitus branch into which main was recently merged

[Bulletin_13_10_2020.en.txt.restored.txt](https://github.com/clulab/habitus/files/9288066/Bulletin_13_10_2020.en.txt.restored.txt)
[Bulletin_03_11_2020.en.txt.restored.txt](https://github.com/clulab/habitus/files/9288067/Bulletin_03_11_2020.en.txt.restored.txt)
.

**Comment by MihaiSurdeanu** [comment]
Interesting... @kwalcock: can you please look at this?

**Comment by kwalcock** [comment]
This is continued at https://github.com/clulab/processors/issues/663 .
