### ISSUE TITLE
Processors may not be enforcing proper BIO-notation

### ISSUE THREAD

**Issue by kwalcock** [clulab/habitus#161]
I'm seeing output that starts immediately with I- like

```
The	O
Hot	O
Dry	I-MISC
Season	I-MISC
2020	B-DATE
:	O
```
and
```
-	O
Financing	O
Credit	O
Mutuel	I-ORG
du	I-ORG
Senegal	I-ORG
(	O
CMS	B-ACRONYM
)	O
CMS	B-ACRONYM
```

**Comment by MihaiSurdeanu** [comment]
Yeah, the CRF layer in the NER encourages well-formed tag sequences, but does not enforce them. I suspect the easiest solution is to flip the first I-* to B-* after the neural NER model is applied.
