### ISSUE TITLE
reading regions from resources directory

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/habitus#171]
I am trying to make a map from files currently stored in resources. The path to the directory is specified in application.conf:
https://github.com/clulab/habitus/blob/2a545a985cc24556a7a6caaa9cd235748a0e8384/src/main/resources/application.conf#L10 
The benefit to storing the files that way is that it will be easy for users to add new region files, but this may be an issue if the code is to be used with a jar. To be investigated.

**Comment by kwalcock** [comment]
I believe this was handled in #172.
