### ISSUE TITLE
PWLWP tokens_allowed limit needs to break selection earlier

### ISSUE THREAD

**Issue by kwalcock** [clulab/habitus#201]
In Matcher.match_scenario there's a loop which limits the length of output: `if current_total + len(sentence[1]) <= tokens_allowed`.  Once we get close to the limit, most sentences will overflow the output and they are skipped until we come across a sometimes very short sentence that can just squeeze in.  That sentence probably won't be a very good one because it is further down the ordered list, and because it can be very short, possibly some kind of header from an article.  For scenario 2a this is "Mining Act".  This probably doesn't hurt ChatGPT, but it does mess up my citation counter, because those two words can be contained within other sentences.  It will also confuse humans who read the context and may not realize the last sentence is chopped off.  I think we should just `break` out of the loop as soon as the next best sentence overflows and not continue adding any more.  As long as tokens_allowed is reasonably large and there aren't any bully, long sentences that block the next sentences, it should be OK to stop early.

**Comment by RazvanDu** [comment]
Fixed.
