### ISSUE TITLE
json vs jsonl

### ISSUE THREAD

**Issue by mithunpaul08** [clulab/habitus#74]
I think right now we are overdoing by printing both .json files and .jsonl files. I think we should pick one. I got before .jsonl definitely. @MihaiSurdeanu do you have any comments? even, i think we must also ask tomek if he is ok with that switch, since he is the one who will eventually use this output. Just opening an issue lest i forget. We don't even need to do this before the deliverables due dec 2021 2nd week . forgot to copy @kwalcock

**Comment by MihaiSurdeanu** [comment]
Whatever Tomek prefers. Please ask him.

**Comment by kwalcock** [comment]
Please mix and match at will.  It should just be a question of commenting out a line and maybe a comma.  I would recommend double checking that N/As are handled as expected in the json outputs.  That seemed to still be in flux when that code was written.

**Comment by mithunpaul08** [comment]
yeah, i already added the N/A ones (though must mention google has trouble rendering the tsv files sometime. looking into it). And yes I will make the code change for choosing between json vs jsonl based on the reply from our consumer (Tomek, who is the owner of the downstream task)

**Comment by mithunpaul08** [comment]
fixed in #84
