### ISSUE TITLE
Habitus: ./var-shell 

### ISSUE THREAD

**Issue by hubert10** [clulab/habitus#75]
Hi all,

The Habitus var- shell  does run the following sentence: "Sowing (15 July - 15 August)". See the output below.

```
(Habitus)>>> Sowing (15 July - 15 August)



(Habitus)>>> 
```
Thanks.

Hubert

**Comment by MihaiSurdeanu** [comment]
This is the expected behavior: out filter marks this sentence as a bad one. See:
https://github.com/clulab/habitus/blob/main/src/main/scala/org/clulab/habitus/HabitusProcessor.scala#L36
