### ISSUE TITLE
no normalized values

### ISSUE THREAD

**Issue by mithunpaul08** [clulab/habitus#78]
IN THE SAED Bulletin_05_05_2020 the following dates are being extracted, but no normalized values are being printed. tests case sent21_8 reflects this and it passes. So something is going wrong while printing this.

----

"variableText" : "sown",
    "valueText" : "before February 15, 2020",
    "sentenceText" : "To date , the distribution according to the cropping calendar , of the sowing carried out at the level of the Dagana delegation is as follows :  -  -  -  9 % of the areas currently cultivated are sown before February 15 , 2020 , i.e. 3,146.92 ha ;  Between the date of February 15 to March 15 , 2020 , are sown 66 % areas developed , i.e. 21,900.73 ha ;  Areas sown beyond March 15 , 2020 cover 25 % of the entire development , i.e. 8,278.18 ha .

**Comment by MihaiSurdeanu** [comment]
Thanks! I'll add a rule for this.

**Comment by MihaiSurdeanu** [comment]
Hi @mithunpaul08:
I added a rule and unit test to capture all 3 extractions in this PR:
https://github.com/clulab/habitus/pull/79
Unit tests pass, so the 3 sowing dates are correctly extracted and normalized.

Can you please look into the printing issue?

**Comment by mithunpaul08** [comment]
fixed this in PR #82 please review and merge. @MihaiSurdeanu

**Comment by mithunpaul08** [comment]
closing this since this issue was fixed and merged into main
